### ISSUE TITLE
How to add products?

### ISSUE THREAD

**Issue by 70shakeel** [MasterKN48/e-commerce#5]
Is there an admin panel where we can add products?

**Comment by MasterKN48** [comment]
yes there is admin panel, which can be done by hard-coding role of user to 1 in database.
See this comments in user schema [ref.](https://github.com/MasterKN48/OpenBook-E-Commerce/blob/a86afbcd5e50cee1b6089fd2cbce527fd2089f2a/model/User.js#L28) . Then login with that hard-coded admin account
